#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🙅 🔗 Styling, testing, and buiding your code before committing ✅✅'

# Check tsconfig standards
# npm run check-types || (
#     echo '✋✋ Failed Type Check 
#             Types are important buddy, please fix them. 😑😑'
#             false;
# )

# Check prettier standards
# npm run check-format || (
#     echo '✋✋ Prettier Says NO 
#             This is strange, but your code is not properly formatted. 😑😑'
#             false;
# )

# Check EsLint standards
# npm run check-lint || (
#     echo '✋✋ EsLint is screaming
#             Please properly fix your code and try again 😑😑'
#             false;
# )

# IF everything passes... try to run build
echo '🤩🤩 Seems this code is clean, Immma try to build it NOW 🤩🤩'

# Error occured while building
# npm run build || (
#     echo '🙀❌🙀Better call Bob 👨‍🔧... Cause your build failed 🙀❌🙀 
#     Next build failed: View the errors above to see why'
#     false;
# )

# if it builds
echo '👊👊 You rock! Commiting now....👊👊'